### ISSUE TITLE
Add ability to choose between logos

### ISSUE THREAD

**Issue by pepsipu** [So-chiru/yappaAmeWallpaper#9]
Hello! I'm a huge fan of this. Would it be possible to add the ability to choose between the ame logo and the tuyu logo, without shifting between them? I only want to display the tuyu logo. Thanks!

**Comment by So-chiru** [comment]
Okay, I'll make an option that display selected logo only. Thank you for your interest!

**Comment by So-chiru** [comment]
@pepsipu Updated both Steam workshop and web version! (https://yappa-ame-wallpaper.vercel.app/generator.html?b=cGluTG9nbz0y)

**Comment by pepsipu** [comment]
Thank you so much!
